NS_Analytics/Models/Answer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Analytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int PeriodId { get; set; }
        public int Value { get; set; }
        public int UserId { get; set; }
        public string Remark { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Question Question { get; set; }
    }
}

NS_Analytics/ViewModels/AnswersViewModel.cs
using NS_Analytics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NS_Analytics.ViewModels
{
    public class AnswersViewModel
    {
        public List<Answer> Answers { get; set; }
    }
}

NS_Analytics/Controllers/MaturityScanController.cs
using Microsoft.AspNet.Identity;
using NS_Analytics.Models;
using NS_Analytics.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NS_Analytics.Controllers
{
    [Authorize(Roles = "Analist, Admin")]
    public class MaturityScanController : Controller
    {
        private NS_AnalyticModelContainer db = new NS_AnalyticModelContainer();
        private ApplicationDbContext identityDb = new ApplicationDbContext();
        private ApplicationUserManager userManager;

        public MaturityScanController()
        {
        }

        public ActionResult REMS1()
        {
            var model = AnswersFilter(categoryId: 5);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS1(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS1");
        }

        public ActionResult REMS2()
        {
            var model = AnswersFilter(categoryId: 6);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS2(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS2");
        }

        public ActionResult REMS3()
        {
            var model = AnswersFilter(categoryId: 7);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS3(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS3");
        }

        public ActionResult REMS4()
        {
            var model = AnswersFilter(categoryId: 8);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS4(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS4");
        }

        public ActionResult REMS5()
        {
            var model = AnswersFilter(categoryId: 9);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS5(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS5");
        }

        public ActionResult REMS6()
        {
            var model = AnswersFilter(categoryId: 10);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult REMS6(AnswersViewModel model)
        {
            SaveAnswerChanges(model);
            return RedirectToAction("REMS6");
        }

        private AnswersViewModel AnswersFilter(int categoryId)
        {
            userManager = new ApplicationUserManager(new ApplicationUserStore(identityDb));
            var user = userManager.FindByName(User.Identity.Name);
            var userId = user.Id;
            if (user.SelectedPeriodId == null)
                return null;

            var periodId = (int)user.SelectedPeriodId;

            var answers = db.Answer.Where(a => a.PeriodId == periodId && a.Question.CategoryId == categoryId && a.UserId == userId).ToList();
            var questions = db.Question.Where(q => q.CategoryId == categoryId).ToList();

            var missingQuestionIds = questions.Select(q => q.Id).Except(answers.Select(a => a.QuestionId));

            foreach (var id in missingQuestionIds)
            {
                db.Answer.Add(new Answer { QuestionId = id, Value = 0, PeriodId = periodId, UserId = userId });
            }
            db.SaveChanges();

            answers = db.Answer.Where(a => a.PeriodId == periodId && a.Question.CategoryId == categoryId && a.UserId == userId).ToList();

            var model = new AnswersViewModel();
            model.Answers = answers;
            return model;
        }

        private void SaveAnswerChanges(AnswersViewModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (var answer in model.Answers)
                {
                    db.Entry(answer).State = EntityState.Modified;
                }
                db.SaveChanges();
            }
        }
    }
}

NS_Analytics/Views/MaturityScan/AnswersForm.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @for (var i = 0; i < Model.Answers.Count; i++)
        {
            <div class="form-group">
                <div class="col-md-12">
                    <div>
                        @Html.HiddenFor(m => m.Answers[i].Id)
                        @Html.HiddenFor(m => m.Answers[i].QuestionId)
                        @Html.HiddenFor(m => m.Answers[i].PeriodId)
                        @Html.HiddenFor(m => m.Answers[i].UserId)
                        @Html.Label("", Model.Answers[i].Question.Value, htmlAttributes: new { @style = "width:700px" })
                        @Html.RadioButtonFor(m => m.Answers[i].Value, 1, htmlAttributes: new { @class = "" }) Ja
                        @Html.RadioButtonFor(m => m.Answers[i].Value, 0, htmlAttributes: new { @class = "" }) Nee
                        @Html.EditorFor(m => m.Answers[i].Remark, new { htmlAttributes = new { @style = "float:right", @class = "form-control" } })
                    </div>
                    <div>

                    </div>
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

NS_Analytics/Views/MaturityScan/REMS1.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan")</li>
    </ul>
</div>

<h2>REMS1</h2>

@Html.Partial("AnswersForm", Model)

NS_Analytics/Views/MaturityScan/REMS2.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan")</li>
    </ul>
</div>

<h2>REMS2</h2>

@Html.Partial("AnswersForm", Model)

NS_Analytics/Views/MaturityScan/REMS3.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan")</li>
    </ul>
</div>

<h2>REMS3</h2>

@Html.Partial("AnswersForm", Model)

NS_Analytics/Views/MaturityScan/REMS4.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan")</li>
    </ul>
</div>

<h2>REMS4</h2>

@Html.Partial("AnswersForm", Model)

NS_Analytics/Views/MaturityScan/REMS5.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan")</li>
    </ul>
</div>

<h2>REMS5</h2>

@Html.Partial("AnswersForm", Model)

NS_Analytics/Views/MaturityScan/REMS6.cshtml
@model NS_Analytics.ViewModels.AnswersViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("REMS1", "REMS1", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS2", "REMS2", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS3", "REMS3", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS4", "REMS4", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS5", "REMS5", "MaturityScan")</li>
        <li>@Html.ActionLink("REMS6", "REMS6", "MaturityScan", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
    </ul>
</div>

<h2>REMS6</h2>

@Html.Partial("AnswersForm", Model)