NS_Analytics/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NS_Analytics.ViewModels
{
    public class UserViewModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Role { get; set; }

        public IList<string> Roles { get; set; }

        public IEnumerable<SelectListItem> AllRoles { get; set; }
        public IList<int> SelectedRoles { get; set; }
        
    }
}

NS_Analytics/Controllers/ManagementController.cs
using Microsoft.AspNet.Identity;
using NS_Analytics.Models;
using NS_Analytics.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NS_Analytics.Controllers
{
    [Authorize(Roles = "Manager, Admin")]
    public class ManagementController : Controller
    {
        private ApplicationDbContext identityDb = new ApplicationDbContext();
        private ApplicationUserManager userManager;

        // GET: Management
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Projects");
        }

        public ActionResult Projects()
        {
            return RedirectToAction("Index", "Projects");
        }

        public async Task<ActionResult> Users()
        {
            userManager = new ApplicationUserManager(new ApplicationUserStore(identityDb));

            var users = identityDb.Users.ToList();
            var models = new List<UserViewModel>();
            foreach (var user in users)
            {
                models.Add(new UserViewModel
                {
                    UserId = user.Id,
                    Roles = await userManager.GetRolesAsync(user.Id),
                    UserName = user.UserName
                });
            }
            return View(models);
        }

        public ActionResult UserEdit(int? id)
        {
            var user = identityDb.Users.Find(id);
            var model = new UserViewModel { UserId = user.Id, UserName = user.UserName, Role = "" };

            var allRoles = identityDb.Roles.ToList();
            model.AllRoles = allRoles.Select(o => new SelectListItem
            {
                Text = o.Name,
                Value = o.Id.ToString()
            });
            model.SelectedRoles = user.Roles.Select(r => r.RoleId).ToList();
            return View(model);
        }

        // POST: Periods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserEdit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                //userManager = new ApplicationUserManager(new ApplicationUserStore(identityDb));
                userManager = new ApplicationUserManager(new ApplicationUserStore(identityDb));

                var currentUser = identityDb.Users.Find(model.UserId);
                var currentRoles = currentUser.Roles;
                var currentRoleIds = currentRoles.Select(r => r.RoleId);

                var selectedRoles = new HashSet<int>();
                if (model.SelectedRoles != null)
                    selectedRoles = new HashSet<int>(model.SelectedRoles);

                foreach (var role in identityDb.Roles.ToList())
                {
                    if (currentRoleIds.Contains(role.Id) && !selectedRoles.Contains(role.Id))
                    {
                        userManager.RemoveFromRole(currentUser.Id, role.Name);
                    }
                    else if (!currentRoleIds.Contains(role.Id) && selectedRoles.Contains(role.Id))
                    {
                        userManager.AddToRole(currentUser.Id, role.Name);
                    }
                }
                return RedirectToAction("Users");
            }
            return View(model);
        }

        public ActionResult AddUser()
        {
            userManager.AddToRoleAsync(1, "Administrator");

            return View();
        }

        public bool AddUserToRole(ApplicationUserManager userManager, int userId, string roleName)
        {
            var idResult = userManager.AddToRoleAsync(userId, roleName);
            return idResult.IsCompleted;
        }
    }
}

NS_Analytics/Views/Management/NavUsers.cshtml
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
        <li>@Html.ActionLink("Periods", "Index", "Periods")</li>
        <li>@Html.ActionLink("Questions", "Index", "Questions")</li>
        <li>@Html.ActionLink("Users", "Users", "Management", htmlAttributes: new { @style = "background-color:#C0C0C0" })</li>
    </ul>
</div>

NS_Analytics/Views/Management/UserEdit.cshtml
@model NS_Analytics.ViewModels.UserViewModel

@{
    ViewBag.Title = "UserEdit";
}

<h2>UserEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllRoles, "Roles", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedRoles, Model.AllRoles, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NS_Analytics/Views/Management/Users.cshtml
@model IEnumerable<NS_Analytics.ViewModels.UserViewModel>

@Html.Partial("NavUsers")

<p>

</p>
<table class="table">
    <tr>
        <th>
            
        </th>
        <th>
            Username
        </th>
        <th>
            Role
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.HiddenFor(m => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @String.Join(";", item.Roles)
            </td>
            <td>
                @Html.ActionLink("Edit", "UserEdit", new { id = item.UserId }) |
                @Html.ActionLink("Details", "UserDetails", new { id = item.UserId }) |
                @Html.ActionLink("Delete", "UserDelete", new { id = item.UserId })
            </td>
        </tr>
    }

</table>